
import Results from "@/components/results";
import HeaderSpin from "./components/header/header";
import useSWR from "swr";
import { API_URL } from "@/app/config/config";
import Loading from "@/components/Loading/Loading";
export const metadata = {
  title: "Spin Game",
  description: "Generated by create next app",
};
export default function RootLayoutSpin({ children }) {
  const fetcher = (...args) => fetch(...args).then((res) => res.json());
  const { data: dbResults } = useSWR(`${API_URL}/api/getSpinResults`, fetcher);
  if (!dbResults) {
    return <Loading />;
  }
  return (
    <div>
      <div className="flex justify-center flex-col md:flex-row">
        <div>
          <HeaderSpin />
          <div className="text-center p-6 pt-0 bg-gray-100 rounded-b-lg shadow-md w-[360px] mx-auto">
            {children}
          </div>
        </div>
        {/* <Results data={dbResults} game={"spin"} /> */}
      </div>
    </div>
  );
}
